definitions:
  config:
    /hst:hst/hst:configurations/iframeprspectivdemo/hst:workspace/hst:channel:
      jcr:primaryType: hst:channel
      hst:name: IFrame Perspective Plugin Demo
      hst:type: website
      /hst:channelinfo:
        jcr:primaryType: hst:channelinfo
