definitions:
  config:
    /hippo:namespaces/iframeprspectivdemo/basedocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: d621a799-9337-48a0-85d3-2da9fca64e4a
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 82e39b78-6e2d-494d-8e2f-276ca551fb3b
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:supertype: ['hippo:document', 'hippostdpubwf:document', 'hippostd:publishableSummary']
          hipposysedit:uri: http://www.onehippo.org/iframeprspectivdemo/nt/1.0
